### ISSUE TITLE
STACK TRACE Error in console

### ISSUE THREAD

**Issue by JoozBrorg** [VeraciousNetwork/PZ-VNGarage#4]
```
STACK TRACE
-----------------------------------------
function: UpdateTireRackSprite -- file: VNTireRackCommon.lua line # 171 | MOD: Veracious Network's Garage
function: ScheduledUpdateCheck -- file: VNTireRack.lua line # 34 | MOD: Veracious Network's Garage
 
ERROR: General     , 1713334458606> 331,244,003> ExceptionLogger.logException> Exception thrown java.lang.RuntimeException: atte
mpted index: getItems of non-table: null at KahluaThread.tableget line:1689.
ERROR: General     , 1713334458606> 331,244,003> DebugLogStream.printException> Stack trace:
java.lang.RuntimeException: attempted index: getItems of non-table: null
        at se.krka.kahlua.vm.KahluaThread.tableget(KahluaThread.java:1689)
        at se.krka.kahlua.vm.KahluaThread.luaMainloop(KahluaThread.java:641)
        at se.krka.kahlua.vm.KahluaThread.call(KahluaThread.java:163)
        at se.krka.kahlua.vm.KahluaThread.pcall(KahluaThread.java:1980)
        at se.krka.kahlua.vm.KahluaThread.pcallvoid(KahluaThread.java:1812)
        at se.krka.kahlua.integration.LuaCaller.pcallvoid(LuaCaller.java:66)
        at se.krka.kahlua.integration.LuaCaller.protectedCallVoid(LuaCaller.java:139)
        at zombie.Lua.Event.trigger(Event.java:64)
        at zombie.Lua.LuaEventManager.triggerEvent(LuaEventManager.java:65)
        at zombie.GameTime.update(GameTime.java:671)
        at zombie.gameStates.IngameState.UpdateStuff(IngameState.java:566)
        at zombie.gameStates.IngameState.updateInternal(IngameState.java:1623)
        at zombie.gameStates.IngameState.update(IngameState.java:1333)
        at zombie.network.GameServer.main(GameServer.java:903)
LOG  : General     , 1713334458607> 331,244,003> -----------------------------------------
STACK TRACE
-----------------------------------------
function: UpdateTireRackSprite -- file: VNTireRackCommon.lua line # 171 | MOD: Veracious Network's Garage
function: ScheduledUpdateCheck -- file: VNTireRack.lua line # 34 | MOD: Veracious Network's Garage
```

**Comment by cdp1337** [comment]
Potential fix implemented, needs verified in a testing environment though.

I'll keep the issue open until verified.

**Comment by cdp1337** [comment]
Published to Steam.

I was never able to reproduce this specific error so I'm leaving the 'pending verified' tag on this until I get notification that it's resolved from those having the issue.
